### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by gwbraa** [globalzon/yaamp#5]
I am getting this error when tried to access the admin the log folder has the permission
in the runtime folder give me this error

REQUEST_URI=/site/frottedessus
2016/08/05 14:28:33 [error] [php] error_log(/var/log/yaamp/debug.log): failed to open stream: Permission denied (/var/web/yaamp/core/common/libUtil.php:122)
Stack trace:
#0 /var/web/framework-1.0.8/web/actions/CInlineAction.php(32): SiteController->actionfrottedessus()
#1 /var/web/framework-1.0.8/web/CController.php(300): CInlineAction->run()
#2 /var/web/framework-1.0.8/web/CController.php(278): SiteController->runAction()
#3 /var/web/framework-1.0.8/web/CController.php(257): SiteController->runActionWithFilters()
#4 /var/web/framework-1.0.8/web/CWebApplication.php(335): SiteController->run()
#5 /var/web/framework-1.0.8/web/CWebApplication.php(123): CWebApplication->runController()
#6 /var/web/framework-1.0.8/base/CApplication.php(134): CWebApplication->processRequest()
#7 /var/web/index.php(16): CWebApplication->run()

REQUEST_URI=/site/frottedessus

Them the debug.log

[2016-08-05 14:25:09] starting apache
[2016-08-05 14:25:12] starting apache
[2016-08-05 14:25:34] starting apache
[2016-08-05 14:25:57] starting apache
[2016-08-05 14:26:11] starting apache
[2016-08-05 14:26:20] starting apache
[2016-08-05 14:26:42] starting apache
[2016-08-05 14:27:05] starting apache
[2016-08-05 14:27:14] starting apache
[2016-08-05 14:27:28] starting apache
[2016-08-05 14:27:50] starting apache
[2016-08-05 14:28:13] starting apache
[2016-08-05 14:28:17] starting apache
[2016-08-05 14:28:35] starting apache
[2016-08-05 14:28:58] starting apache
[2016-08-05 14:29:19] starting apache
[2016-08-05 14:29:29] CronjobController::actionRun 3

I follow all the steps when I tried to run the run.sh I get this error too

./run.sh: line 8: ./stratum: No such file or directory

**Comment by goodthebest** [comment]
@gwbraa if you still couldn't get it done, I can do it, just msg me
